name: example-simulate-complex
channels:
  - conda-forge
dependencies:
  - openmm ==7.7.0
  - openmmforcefields ==0.11.2
  - pdbfixer ==1.8.1
  - rdkit ==2022.03.5
  - openff-toolkit ==0.13.0 
  - openff-units ==0.2.0
